name: App build
on:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review, unlabeled]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v6

      - name: Install mops
        uses: caffeinelabs/setup-mops@v1

      - name: Make sure moc is installed
        run: mops toolchain bin moc || mops toolchain use moc latest

      - name: Run mops tests
        run: mops test

      - name: Build example actor
        working-directory: example
        run: $(mops toolchain bin moc) $(mops sources) actor.mo --idl

      - name: Get didc
        run: |
          release=$(curl --silent "https://api.github.com/repos/dfinity/candid/releases/latest" | awk -F\" '/tag_name/ { print $4 }')
          mkdir -p /home/runner/bin
          curl -fsSL https://github.com/dfinity/candid/releases/download/$release/didc-linux64 > /home/runner/bin/didc
          chmod +x /home/runner/bin/didc
          echo "/home/runner/bin" >> $GITHUB_PATH

      - name: Check public did file against icrc84 standard
        run: |
          didc check example/actor.did icrc-84.did
          didc check icrc-84.did example/actor.did

  format:
    name: Check formatting
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: "24"

      - name: Install prettier plugin
        run: npm install --save-dev prettier prettier-plugin-motoko

      - name: Run prettier check
        run: npx prettier --check --plugin=prettier-plugin-motoko '**/*.{mo,json,md}'
